In [3]:
#1.
from sklearn.datasets import load_wine
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pandas as pd

X, y = load_wine(return_X_y=True, as_frame=True)
rfe=RFE(LogisticRegression(max_iter=10000),n_features_to_select=3)
rfe.fit(X,y)
print(X.columns[rfe.support_].tolist())

#Perform Recursive Feature Elimination (RFE) using Logistic Regression to select the top 3 features.

#Expected Output:
#Top 3 selected features using RFE: ['alcohol', 'flavanoids', 'od280/od315_of_diluted_wines']


['alcohol', 'flavanoids', 'od280/od315_of_diluted_wines']


In [7]:
#2.
from sklearn.datasets import load_digits
from sklearn.decomposition import PCA
import pandas as pd

X, y = load_digits(return_X_y=True, as_frame=True)
pca=PCA(n_components=3)
X_reduced=pca.fit_transform(X)
print(X_reduced.shape)

#Perform PCA for dimensionality reduction and reduce the dataset to 3 components.

#expected output:
    
#Transformed dataset (3 components):
 #[[ -1.2594664   21.27488439  -9.46305689]
 #[  7.9576113  -20.76870018   4.43950399]
 #[  6.99192304  -9.9559863    2.95856164]
 #...
 #[ 10.80128394  -6.96025023   5.59956528]
 #[ -4.87210013  12.42395227 -10.17088928]
 #[ -0.34438951   6.36555114  10.77371663]]


(1797, 3)


In [8]:
#3.
from sklearn.datasets import load_iris
from sklearn.manifold import TSNE
import pandas as pd

X, y = load_iris(return_X_y=True, as_frame=True)
tsne=TSNE(n_components=2,random_state=42)
X_reduced=tsne.fit_transform(X)
print(X_reduced.shape)
#Perform t-SNE dimensionality reduction to reduce the dataset to 2 dimensions.


(150, 2)


In [11]:
#4.
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
# Create a mock dataset of users and movie ratings
data = {'User': ['U1', 'U2', 'U3', 'U4', 'U5'],
        'Movie A': [5, 4, 0, 1, 2],
        'Movie B': [4, 0, 5, 2, 3],
        'Movie C': [1, 2, 4, 5, 0],
        'Movie D': [0, 1, 2, 3, 4]}

df = pd.DataFrame(data)
sim=cosine_similarity(ratings)[0]
most_similar=ratings.index[sim.argsort()[-2]
recommend=ratings.loc[most_similar][ratings.loc['U1']==0
print recommend

#Use Cosine Similarity to recommend movies to User U1 based on their similarity to other users.

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2712375069.py, line 14)

In [12]:
#5.
from sklearn.datasets import load_digits
from sklearn.decomposition import PCA
import pandas as pd

X, y = load_digits(return_X_y=True, as_frame=True)
pca=PCA(n_components=2)
X_reduced=pca.fit_transform(X)
print(X_reduced.shape)


#Expected output:
#Reduced shape: (1797, 2)


(1797, 2)
