In [1]:
#1.
from sklearn.decomposition import PCA
import numpy as np

X = np.random.rand(5, 3)
pca = PCA(n_components=4)
X_pca = pca.fit_transform(X)


ValueError: n_components=4 must be between 0 and min(n_samples, n_features)=3 with svd_solver='full'

In [2]:
#2.
import numpy as np

user_factors = np.random.rand(3, 4)
item_factors = np.random.rand(5, 3)
pred = np.dot(user_factors, item_factors)


ValueError: shapes (3,4) and (5,3) not aligned: 4 (dim 1) != 5 (dim 0)

In [3]:
#3.
import pickle
pickle.save(model, open('model.pkl', 'wb'))


AttributeError: module 'pickle' has no attribute 'save'

In [4]:
#4.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
rfe = RFE(model, n_features_to_select=5)
X_selected = rfe.fit_transform(X, y)
print(X_selected.shape)

NameError: name 'y' is not defined

In [5]:
#5.

from sklearn.feature_selection import SelectKBest, f_classif
import pandas as pd

df = pd.DataFrame({
    'age': [20, 30, 40],
    'gender': ['M', 'F', 'M'],
    'target': [1, 0, 1]
})

X = df[['age', 'gender']]
y = df['target']

selector = SelectKBest(score_func=f_classif, k=1)
X_new = selector.fit_transform(X, y)

print("Shape:", X_new.shape)


ValueError: could not convert string to float: 'M'

In [6]:
#6.
import pandas as pd
movies = pd.DataFrame({
    'title': ['Inception', 'Interstellar', 'Dark Knight', 'Tenet'],
    'description': [
        'dream within a dream and sci-fi thriller',
        'space time travel and love across galaxies',
        'dark superhero action and Gotham city',
        'reversed time logic and spy action'
    ]
})
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
tfidf = TfidfVectorizer()
matrix = tfidf.fit_transform(movies['title'])  # Mistakenly used 'title'
similarity = cosine_similarity(matrix)
print(similarity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
#7.
movies = pd.DataFrame({
    'title': ['A', 'B', 'C'],
    'description': ['action drama', 'sci-fi thriller', 'romantic comedy']
})
from sklearn.feature_extraction.text import TfidfVectorizer
​
tfidf = TfidfVectorizer()
matrix = tfidf.fit_transform(movies['desc'])  # typo!
​


SyntaxError: invalid non-printable character U+200B (334984700.py, line 7)

In [8]:
#8.
import pandas as pd

ratings = pd.DataFrame({
    'Movie1': [5, 4, 1],
    'Movie2': [3, 2, 5],
    'Movie3': [0, 1, 4]
}, index=['UserA', 'UserB', 'UserC'])
from sklearn.metrics.pairwise import cosine_similarity

sim = cosine_similarity(ratings)
print(sim)



[[1.         0.97302555 0.52925612]
 [0.97302555 1.         0.60609153]
 [0.52925612 0.60609153 1.        ]]


In [9]:
#9.
import pandas as pd

df = pd.DataFrame({
    'user': ['A', 'B', 'A', 'C'],
    'movie': ['X', 'Y', 'Y', 'X'],
    'rating': [4, 5, 3, 2]
})
top_movie = df.groupby('movie')['ratings'].mean().idxmax()
print("Top Movie:", top_movie)


KeyError: 'Column not found: ratings'

In [10]:
#10.
data = pd.DataFrame({
    'movie': ['A', 'B', 'A', 'C'],
    'rating': [5, 3, 4, 2]
})
avg_ratings = data.groupby('movie')['rating'].mean()
high_rated = avg_ratings[avg_ratings > 4.0]
print(high_rated['movie'])


KeyError: 'movie'